#!/bin/bash

# Created by @CesarHackGray 

# Creado el 26 de mayo del 2019

# anti-infackeable :v bloqueado por @CesarHackGray

# servicio de ayuda https://t.me/CesarGray



z="
";BBz='/ __';yCz='n';NEz='...\';dz='prin';vBz='olor';TBz='ckGr';YEz='vali';BDz='/.ba';bCz='e un';dEz='}';rCz='....';GEz='hrc"';jBz='2]$W';ICz='whil';cBz=':$R ';QBz=' by ';Fz='  G=';MEz='."';qDz='loca';QCz='-z $';wDz='tps:';Hz='3[1;';SDz='ay/r';VDz='ownl';Pz='m'\''';DDz='fi';hCz=' $co';mBz=':$G ';Oz='1;35';rBz='s ca';CEz='cuta';HEz='exit';pz='  | ';oDz='r fu';Wz=' ban';mz='  ._';QDz='-Hac';sBz='mbia';Jz='Y='\''\';Vz='tion';JBz='  \/';UBz='ay"';eCz='"';ODz='om/C';eBz='@loc';lBz='erde';tBz='ran ';pCz='.."';mDz='hrc';WCz=']$W ';TCz=' do';ECz='ra n';LCz='p " ';Dz='m'\''  ';JCz='e re';ZCz='r es';DCz='r pa';FCz='ethu';KEz='"2")';UCz='$G[$';yDz='me/C';jz='   _';KBz='\/  ';OBz=' Cre';fz='$G"';aBz=' eje';DEz='$G s';tDz=' Con';PEz='rc &';lDz='.bas';bBz='mplo';YDz='er/.';sDz=')"';fCz='done';KCz='ad -';dCz='cion';VEz='or n';Zz='echo';rz='/ _|';REz='*)';UEz=' Err';uBz='de c';gDz='nsta';tCz='if [';GBz='__ (';Ez='    ';LEz='lor.';wBz=' a a';xBz='zul ';FBz='___|';NDz='nt.c';ACz='$G[*';ZEz='do"';TDz='elea';cDz='inst';cEz='esac';IDz='/raw';SCz='r ];';hDz='ll.l';iBz='$W#"';CBz=' \| ';pBz=' cat';sz='____';XCz='por ';wz='__  ';MDz='onte';RBz='@Ces';NCz=' col';GCz='nter';jDz='mv ~';LBz='   "';fBz='alho';Mz='34m'\''';xz='\ | ';xDz='//t.';lCz='cand';WBz='1]$W';qCz='..."';iCz='lor ';sCz='\n"';ZDz='bash';Iz='32m'\''';ez='tf "';vz=' < \';FDz='wget';xCz=' the';jCz='in';kDz='1 ~/';Gz=''\''\03';nDz=' El ';IBz='___/';WEz='umer';gBz='st$W';Qz='C='\''\';bDz='&>> ';uDz='tact';FEz='e ~/';gz='slee';PBz='ated';hz='p 2';tz=' | |';HBz='  /_';az=' $(c';WDz='oad/';vDz='a ht';oBz=' las';RCz='colo';fEz='ce ~';BCz=']$R ';YCz='favo';Uz='func';fDz='rm i';yz='  |"';EEz='ourc';AEz='Gray';hBz=':$B~';iz=' "  ';SEz='$R*$';VBz='"$G[';dDz='all.';eDz='log';VCz='R*$G';lz=' __.';Xz='ner ';PCz='& [ ';aEz='bann';OCz='or &';XDz='mast';kCz='"1")';BEz=' Eje';XEz='o in';nBz='*]$W';ABz='  \ ';IEz=' 5';Nz='M='\''\';Tz='0m'\''';JEz=';;';cz=')';oCz='p 1';RDz='k-Gr';LDz='serc';wCz='c ];';nCz='lor"';MCz='=> "';aCz='crib';pDz='e co';kBz='or v';cCz='a op';aDz='rc1 ';Kz='1;33';mCz='o co';Bz='033[';CCz='Colo';Lz='  B=';oz='__ "';yBz=':)"';bEz='er';qBz='peta';OEz='n"';uz='__|"';XBz=' Col';bz='lear';iDz='og';UDz='se-d';EDz='cd ~';vCz='ashr';uCz='~/.b';Sz='W='\''\';HDz='ps:/';PDz='esar';SBz='arHa';ADz='rm ~';dBz='root';KDz='hubu';JDz='.git';eEz='sour';TEz='G]$W';qz='   |';NBz='"$W ';EBz='  |_';HCz='$Y"';YBz='or r';gCz='case';kz='___ ';rDz='do :';QEz='>> i';Rz='1;36';nz='_  .';Yz='() {';GDz=' htt';Cz='1;31';ZBz='ojo ';DBz=' |_|';MBz=' -e ';CDz='shrc';Az='R='\''\';
eval "$Az$Bz$Cz$Dz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Fz$Gz$Hz$Iz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Jz$Bz$Kz$Dz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Lz$Gz$Hz$Mz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Nz$Bz$Oz$Pz$z$Qz$Bz$Rz$Pz$z$Sz$Bz$Tz$z$Uz$Vz$Wz$Xz$Yz$z$Zz$az$bz$cz$z$Zz$z$Zz$z$dz$ez$fz$z$gz$hz$z$Zz$iz$Ez$Ez$Ez$jz$kz$lz$Ez$mz$nz$oz$z$Zz$iz$Ez$Ez$Ez$pz$qz$rz$sz$pz$tz$uz$z$Zz$iz$Ez$Ez$Ez$pz$Ez$vz$wz$xz$tz$yz$z$Zz$iz$Ez$Ez$Ez$pz$qz$ABz$BBz$CBz$DBz$yz$z$Zz$iz$Ez$Ez$Ez$EBz$FBz$GBz$sz$HBz$IBz$uz$z$Zz$iz$Ez$Ez$Ez$Ez$Ez$JBz$Ez$KBz$Ez$LBz$z$Zz$MBz$NBz$Ez$Ez$Ez$OBz$PBz$QBz$RBz$SBz$TBz$UBz$z$Zz$z$Zz$MBz$VBz$WBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$z$Zz$MBz$VBz$jBz$XBz$kBz$lBz$aBz$bBz$mBz$dBz$eBz$fBz$gBz$hBz$iBz$z$Zz$z$Zz$MBz$VBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$z$Zz$z$dz$ez$ACz$BCz$CCz$DCz$ECz$FCz$GCz$HCz$z$ICz$JCz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$TCz$z$dz$ez$UCz$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$z$fCz$z$gCz$hCz$iCz$jCz$z$kCz$z$dz$ez$ACz$WCz$CCz$lCz$mCz$nCz$z$gz$oCz$z$dz$ez$pCz$z$gz$hz$z$dz$ez$qCz$z$gz$hz$z$dz$ez$rCz$sCz$z$gz$oCz$z$tCz$MBz$uCz$vCz$wCz$xCz$yCz$z$ADz$BDz$CDz$z$DDz$z$EDz$z$FDz$GDz$HDz$IDz$JDz$KDz$LDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$dDz$eDz$z$fDz$gDz$hDz$iDz$z$jDz$BDz$CDz$kDz$lDz$mDz$z$Zz$MBz$VBz$nBz$nDz$RCz$oDz$pDz$qDz$rDz$sDz$z$Zz$MBz$VBz$nBz$tDz$uDz$vDz$wDz$xDz$yDz$PDz$AEz$eCz$z$Zz$MBz$VBz$nBz$BEz$CEz$DEz$EEz$FEz$lDz$GEz$z$HEz$IEz$z$JEz$z$KEz$z$dz$ez$ACz$WCz$CCz$lCz$mCz$LEz$MEz$z$dz$ez$qCz$z$gz$oCz$z$dz$ez$qCz$z$gz$hz$z$dz$ez$qCz$z$gz$hz$z$dz$ez$NEz$OEz$z$gz$oCz$z$tCz$MBz$uCz$vCz$wCz$xCz$yCz$z$ADz$BDz$CDz$z$DDz$z$EDz$z$FDz$GDz$HDz$IDz$JDz$KDz$LDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$PEz$QEz$gDz$hDz$iDz$z$fDz$gDz$hDz$iDz$z$Zz$MBz$VBz$nBz$nDz$RCz$oDz$pDz$qDz$rDz$sDz$z$Zz$MBz$VBz$nBz$tDz$uDz$vDz$wDz$xDz$yDz$PDz$AEz$eCz$z$Zz$MBz$VBz$nBz$BEz$CEz$DEz$EEz$FEz$lDz$GEz$z$Zz$z$JEz$z$REz$z$gz$oCz$z$Zz$MBz$VBz$SEz$TEz$UEz$VEz$WEz$XEz$YEz$ZEz$z$gz$hz$z$aEz$bEz$z$JEz$z$cEz$z$dEz$z$aEz$bEz$z$eEz$fEz$BDz$CDz"
