#/bin/bash

# Created by @CesarHackGray 

# Creado el 26 de mayo del 2019 :v
# quieres ver como funciona mi script o quieres adueñarte de ella :v

# anti-infackeable >> bloqueado por @CesarHackGray



# servicio de ayuda https://t.me/CesarGray



z="
";yz='  |"';PEz='n"';NEz='."';lz=' __.';yDz='//t.';aEz='do"';kDz='mv ~';uCz='if [';tDz=')"';ACz='$G[*';cCz='e un';qCz='.."';VCz='$G[$';ZBz='ojo ';TDz='ay/r';tz=' | |';Rz='1;36';ADz='n';RDz='-Hac';LEz='"2")';jCz='lor ';DBz=' |_|';WBz='1]$W';gDz='rm i';hCz='case';oDz=' El ';PDz='om/C';EDz='fi';KCz='e re';SCz='colo';hDz='nsta';hBz=':$B~';ODz='nt.c';dCz='a op';NCz='=> "';fCz='"';VEz=' Err';BDz='rm ~';eCz='cion';wz='__  ';MEz='lor.';qz='   |';eEz='}';FCz='ethu';nBz='*]$W';jDz='og';BEz='Gray';sz='____';wDz='a ht';sDz='do :';pz='  | ';Jz='Y='\''\';Uz='func';mBz=':$G ';wBz=' a a';gBz='st$W';dEz='esac';Az='R='\''\';cDz='&>> ';sCz='....';MDz='serc';UCz=' do';uBz='de c';jz='   _';iDz='ll.l';HEz='hrc"';GBz='__ (';FDz='cd ~';IBz='___/';az=' $(c';yCz=' the';GDz='wget';RCz='-z $';FEz='ourc';fz='$G"';ICz=')$Y"';DEz='cuta';pBz=' car';mz='  ._';XDz='oad/';VDz='se-d';DDz='shrc';iz=' "  ';ZEz='vali';KBz='\/  ';YBz='or r';ez='tf "';dDz='inst';TCz='r ];';SDz='k-Gr';PCz='or &';UDz='elea';WEz='or n';SEz='*)';rBz='s ca';fEz='sour';gCz='done';MCz='p " ';bEz='bann';YCz='por ';dBz='root';OEz='...\';JDz='/raw';tBz='ran ';CBz=' \| ';lBz='erde';XBz=' Col';UBz='ray"';JEz=' 5';SBz='sarH';Kz='1;33';cEz='er';MBz=' -e ';oz='__ "';XCz=']$W ';aBz=' eje';dz='prin';mCz='cand';uz='__|"';gz='slee';rz='/ _|';FBz='___|';Ez='    ';kz='___ ';Nz='M='\''\';OBz='  Cr';lCz='"1")';JCz='whil';mDz='.bas';Vz='tion';YDz='mast';REz='>> i';Cz='1;31';Bz='033[';QBz='d by';YEz='o in';wCz='ashr';xBz='zul ';HBz='  /_';vCz='~/.b';nz='_  .';IDz='ps:/';NBz='"$W ';rCz='..."';fBz='alho';aCz='r es';UEz='G]$W';HCz='(1/2';vz=' < \';vDz='tact';QEz='rc &';RBz=' @Ce';CCz='Colo';Xz='ner ';OCz=' col';hz='p 2';GEz='e ~/';Qz='C='\''\';EEz='$G s';Lz='  B=';xDz='tps:';bz='lear';WCz='R*$G';TBz='ackG';QCz='& [ ';Oz='1;35';vBz='olor';eDz='all.';pCz='p 1';pDz='r fu';xz='\ | ';QDz='esar';bDz='rc1 ';AEz='me/C';bCz='crib';ZDz='er/.';fDz='log';TEz='$R*$';WDz='ownl';kBz='or v';CDz='/.ba';cz=')';Yz='() {';PBz='eate';Hz='3[1;';eBz='@loc';oCz='lor"';qDz='e co';Pz='m'\''';kCz='in';xCz='c ];';LBz='   "';Sz='W='\''\';bBz='mplo';qBz='peta';Iz='32m'\''';aDz='bash';KDz='.git';uDz=' Con';Wz=' ban';BCz=']$R ';BBz='/ __';tCz='\n"';NDz='onte';XEz='umer';nCz='o co';Zz='echo';HDz=' htt';CEz=' Eje';Mz='34m'\''';LDz='hubu';JBz='  \/';Dz='m'\''  ';LCz='ad -';ABz='  \ ';ZCz='favo';ECz='ra n';lDz='1 ~/';IEz='exit';nDz='hrc';rDz='loca';EBz='  |_';iCz=' $co';gEz='ce ~';KEz=';;';Tz='0m'\''';jBz='2]$W';oBz=' las';VBz='"$G[';DCz='r pa';iBz='$W#"';Gz=''\''\03';GCz='nter';yBz=':)"';Fz='  G=';cBz=':$R ';sBz='mbia';
eval "$Az$Bz$Cz$Dz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Fz$Gz$Hz$Iz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Jz$Bz$Kz$Dz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Lz$Gz$Hz$Mz$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Ez$Nz$Bz$Oz$Pz$z$Qz$Bz$Rz$Pz$z$Sz$Bz$Tz$z$Uz$Vz$Wz$Xz$Yz$z$Zz$az$bz$cz$z$Zz$z$Zz$z$dz$ez$fz$z$gz$hz$z$Zz$iz$Ez$Ez$Ez$jz$kz$lz$Ez$mz$nz$oz$z$Zz$iz$Ez$Ez$Ez$pz$qz$rz$sz$pz$tz$uz$z$Zz$iz$Ez$Ez$Ez$pz$Ez$vz$wz$xz$tz$yz$z$Zz$iz$Ez$Ez$Ez$pz$qz$ABz$BBz$CBz$DBz$yz$z$Zz$iz$Ez$Ez$Ez$EBz$FBz$GBz$sz$HBz$IBz$uz$z$Zz$iz$Ez$Ez$Ez$Ez$Ez$JBz$Ez$KBz$Ez$LBz$z$Zz$MBz$NBz$Ez$Ez$Ez$OBz$PBz$QBz$RBz$SBz$TBz$UBz$z$Zz$z$Zz$MBz$VBz$WBz$XBz$YBz$ZBz$aBz$bBz$cBz$dBz$eBz$fBz$gBz$hBz$iBz$z$Zz$MBz$VBz$jBz$XBz$kBz$lBz$aBz$bBz$mBz$dBz$eBz$fBz$gBz$hBz$iBz$z$Zz$z$Zz$MBz$VBz$nBz$oBz$pBz$qBz$rBz$sBz$tBz$uBz$vBz$wBz$xBz$yBz$z$Zz$z$dz$ez$ACz$BCz$CCz$DCz$ECz$FCz$GCz$HCz$ICz$z$JCz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$TCz$UCz$z$dz$ez$VCz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$dCz$eCz$fCz$z$gCz$z$hCz$iCz$jCz$kCz$z$lCz$z$dz$ez$ACz$XCz$CCz$mCz$nCz$oCz$z$gz$pCz$z$dz$ez$qCz$z$gz$hz$z$dz$ez$rCz$z$gz$hz$z$dz$ez$sCz$tCz$z$gz$pCz$z$uCz$MBz$vCz$wCz$xCz$yCz$ADz$z$BDz$CDz$DDz$z$EDz$z$FDz$z$GDz$HDz$IDz$JDz$KDz$LDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$bDz$cDz$dDz$eDz$fDz$z$gDz$hDz$iDz$jDz$z$kDz$CDz$DDz$lDz$mDz$nDz$z$Zz$MBz$VBz$nBz$oDz$SCz$pDz$qDz$rDz$sDz$tDz$z$Zz$MBz$VBz$nBz$uDz$vDz$wDz$xDz$yDz$AEz$QDz$BEz$fCz$z$Zz$MBz$VBz$nBz$CEz$DEz$EEz$FEz$GEz$mDz$HEz$z$IEz$JEz$z$KEz$z$LEz$z$dz$ez$ACz$XCz$CCz$mCz$nCz$MEz$NEz$z$dz$ez$rCz$z$gz$pCz$z$dz$ez$rCz$z$gz$hz$z$dz$ez$rCz$z$gz$hz$z$dz$ez$OEz$PEz$z$gz$pCz$z$uCz$MBz$vCz$wCz$xCz$yCz$ADz$z$BDz$CDz$DDz$z$EDz$z$FDz$z$GDz$HDz$IDz$JDz$KDz$LDz$MDz$NDz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$VDz$WDz$XDz$YDz$ZDz$aDz$QEz$REz$hDz$iDz$jDz$z$gDz$hDz$iDz$jDz$z$Zz$MBz$VBz$nBz$oDz$SCz$pDz$qDz$rDz$sDz$tDz$z$Zz$MBz$VBz$nBz$uDz$vDz$wDz$xDz$yDz$AEz$QDz$BEz$fCz$z$Zz$MBz$VBz$nBz$CEz$DEz$EEz$FEz$GEz$mDz$HEz$z$Zz$z$KEz$z$SEz$z$gz$pCz$z$Zz$MBz$VBz$TEz$UEz$VEz$WEz$XEz$YEz$ZEz$aEz$z$gz$hz$z$bEz$cEz$z$KEz$z$dEz$z$eEz$z$bEz$cEz$z$fEz$gEz$CDz$DDz"
