#!/data/data/com.termux/files/usr/bin/bash
#Created on 16/July/2017 by Ivam3
#Last update 02/dic/2018
#
#	Var
		R='\033[1;31m'
                G='\033[1;32m'
                Y='\033[1;33m'
                B='\033[1;34m'
                M='\033[1;35m'
                C='\033[1;36m'
                W='\033[0m'

if [ ! -e ~/version ]; then
	sleep 3
	echo
	echo
	echo
echo $(clear)
echo -e "$G===============================================================$R"
echo "                         __  __ ____  _____"
echo "                        |  \/  / ___||  ___|"
echo "                        | |\/| \___ \| |_"
echo "                        | |  | |___) |  _|"
echo "                        |_|  |_|____/|_|"
echo
echo -e "$G==============================================================="
echo -e $C"	                    ______    "
echo "	                 .-        -. "
echo "	                /            \         "
echo "	               |,  .-.  .-.  ,|      "
echo "	               | )(_ /  \_ )( |"
echo "	               |/     /\     \|    "
echo -e $C"	   $Y  (@_   $C    <__    ^^    __>        "
echo -e $C"      _       ) $R\_______$C""\__|IIIIII|__/$R""_____________________ "
echo -e $C"     (_)$Y\@8@8{}<$R""___________________________________________$Y> "
echo -e $C"              )_/  $C       \ IIIIII /                    "
echo -e $C"	   $Y  (@        $C    --------                      "
echo -e $C"       	         version msf >$R v (multi)"
echo -e " 	          Creador : $Y""Cesar Hacker The Gray"
echo -e $R"     msf$R Instala cualquier version que quieras$R de metasploit"
echo
echo -e "     $G Escribe la version de metasploit que quieres tener\n"
echo 
echo
printf "$C[Gray] $R La version que quiero es$B? $M>>$Y "
	while read ANSW && [ -z $ANSW ]; do
		printf "$R[*] Contactame https://t.me/CesarGray\n$W"
	done
	echo "export version=$ANSW" > ~/version
fi
source ~/version

echo $(clear)
        printf "$R"
	echo  "               #Somos1somostodos"
        printf "$G"
        echo $(clear)
echo -e $C"========================================================================"
echo -e $G"            Metasploit Hackeando desde android con Cesar Hack Gray   "
echo -e $C"========================================================================"
echo -e $R""
echo "	 									"
echo "   	                  ..:::::::::..		"
echo "   	               ..:::aad8888888baa:::..	"
echo "   	           .::::d:?88888888888?::8b::::.	"
echo "   	         .:::d8888:?88888888??a888888b:::.	"
echo "   	       .:::d8888888a8888888aa8888888888b:::.	"
echo "   	      ::::dP::::::::88888888888::::::::Yb::::	"
echo "   	     ::::dP:::::::::Y888888888P:::::::::Yb::::	"
echo "   	    ::::d8:::::::::::Y8888888P:::::::::::8b::::	"
echo "   	   .::::88::::::::::::Y88888P::::::::::::88::::.	"
echo "   	   :::::Y8baaaaaaaaaa88P:T:Y88aaaaaaaaaad8P:::::	"
echo "   	   :::::::Y88888888888P::|::Y88888888888P:::::::	"
echo "   	   ::::::::::::::::888:::|:::888::::::::::::::::	"
echo "   	    :::::::::::::::8888888888888b::::::::::::::	"
echo "   	    :::::::::::::::88888888888888::::::::::::::	"
echo "   	     :::::::::::::d88888888888888::::::::::::: 	"
echo "   	      ::::::::::::88::88::88:::88::::::::::::	"
echo "   	        ::::::::::88::88::88:::88::::::::::	"
echo "   	          ::::::::88::88::P::::88::::::::	"
echo "   	            ::::::88::88:::::::88::::::	"
echo "   	                :::::::::::::::::::	"
echo "   	                     ::::::::: 	"
echo ""
echo -e -$C	"           Creador:$R "CesarHackGray" $C( Edo Hacking- ) "
echo -e "             Comunicate : $R "Telegram" $C( https://t.me/CesarGray "
echo -e "       Seguidores : $R Mickey Hacker >> Charly Hacker The Gray  "
echo -e $C"========================================================================"
echo -e $G"                Metasploit >> Cesar >> Mickey >> Charly  "
echo -e $C"========================================================================"
echo -e "$C"
echo "           Bamos a instalar esta version $version de metasploit"
echo 
printf "                  $C Presiona$M enter$C para$M continuar"
        read enter
printf "$W
"
echo $(clear)
echo
echo
echo
echo -e "$G ##############################################"
echo -e "$C [Gray] $G Instalando requisitos y repositorios"
echo -e "$G ##############################################"
echo
echo
sleep 3
dpkg --configure -a
apt update -y && apt upgrade -y
apt autoremove
apt install ruby
apt install -y util-linux
apt install -y autoconf util-linux bison clang coreutils axel curl findutils git apr apr-util libffi-dev libgmp-dev libpcap-dev postgresql-dev readline-dev libsqlite-dev openssl-dev libtool libxml2-dev libxslt-dev ncurses-dev pkg-config wget make ruby-dev libgrpc-dev termux-tools ncurses-utils ncurses unzip zip tar postgresql termux-elf-cleaner
echo "
"
echo $(clear)
echo
echo
echo
echo
echo -e "$G ++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "$C [Gray] $G Checando Metasploit si esta en HOME"
echo -e "$G ++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo
echo
echo
sleep 3
if [ -d ~/metasploit-framework ]; then 
	rm -rf ~/metasploit-framework 
fi
find $HOME -name "*$version.tar.gz" -type f -delete
find $HOME -name "metasploit*" -type d -delete

echo $(clear)
echo
echo
echo
echo -e "$G ========================================="
echo -e "$C [Gray] $G Instalando metasploit-framework"
echo -e "$G ========================================="
echo
echo
echo
echo
sleep 4
printf "$B"
cd $HOME
axel --alternate https://github.com/rapid7/metasploit-framework/archive/$version.tar.gz
tar -xf $HOME/metasploit-framework-$version.tar.gz
mv $HOME/metasploit-framework-$version $HOME/metasploit-framework
rm $HOME/metasploit-framework-$version.tar.gz
cd $HOME/metasploit-framework
sed '/rbnacl/d' -i Gemfile.lock
sed '/rbnacl/d' -i metasploit-framework.gemspec

echo $(clear)
echo
echo
echo
echo -e "$G ×××××××××××××××××××××××××××××"
echo -e "$G [Gray] $C Instalando gemas"
echo -e "$G ×××××××××××××××××××××××××××××"
echo
echo
sleep 4
printf "$G"
gem update --system
gem install bundler
sed 's|nokogiri (1.*)|nokogiri (1.8.0)|g' -i Gemfile.lock
ln -sf $PREFIX/include/libxml2/libxml $PREFIX/include/
gem install nokogiri -v 1.8.0 -- --use-system-libraries
#sed 's|grpc (.*|grpc (1.4.1)|g' -i $HOME/metasploit-framework/Gemfile.lock
#gem unpack grpc -v 1.4.1
#cd grpc-1.4.1
#curl -LO https://raw.githubusercontent.com/grpc/grpc/v1.4.1/grpc.gemspec
#curl -LO https://raw.githubusercontent.com/Cesar-Hack-Gray/release-download/master/extconf.patch
#patch -p1 < extconf.patch
#gem build grpc.gemspec
#gem install grpc-1.4.1.gem
#cd ..
#rm -r grpc-1.4.1
sleep 4
echo $(clear)
cd $HOME/metasploit-framework
bundle install -j5
$PREFIX/bin/find -type f -executable -exec termux-fix-shebang \{\} \;
rm ./modules/auxiliary/gather/http_pdf_authors.rb
if [ -e $PREFIX/bin/msfconsole ] || [ -L $PREFIX/bin/msfconsole ]; then
        rm $PREFIX/bin/msfconsole
fi
if [ -e $PREFIX/bin/msfvenom ] || [ -L $PREFIX/bin/msfvenom ]; then
        rm $PREFIX/bin/msfvenom
fi
ln -sf $HOME/metasploit-framework/msfconsole /data/data/com.termux/files/usr/bin/
ln -sf $HOME/metasploit-framework/msfvenom /data/data/com.termux/files/usr/bin/
termux-elf-cleaner /data/data/com.termux/files/usr/lib/ruby/gems/2.5.0/gems/pg-0.20.0/lib/pg_ext.so
echo $(clear)
echo
echo
echo
echo -e "$G ÷÷÷÷÷÷÷÷÷÷÷÷+=+÷+÷+÷+÷+÷+÷+=++=+"
echo -e "$C [Gray] $G Creando databases"
echo -e "$G +÷+÷+÷+÷+÷+÷+÷+÷+÷+÷+÷+÷+÷+÷+=+="
echo
echo
echo
echo
sleep 4
printf "$Y
"
mv $HOME/metasploit-framework/database.yml $HOME/metasploit-framework/config
cd $HOME/metasploit-framework/config
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql
pg_ctl -D $PREFIX/var/lib/postgresql start
createuser msf
createdb msf_database
pg_ctl -D $PREFIX/var/lib/postgresql start
sed -i "4a pg_ctl -D $PREFIX/var/lib/postgresql start" $PREFIX/etc/bash.bashrc
sed -i "5a clear" $PREFIX/etc/bash.bashrc

echo $(clear)
echo
echo
echo
echo
echo -e "$G XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo -e "$G [Gray] $G Cargandooo script"
echo -e "$G XXXXXXXXXXXXXXXXXXXXXXXXXXCX"
echo
echo
echo
echo
sleep 3
echo $(clear)
printf "$R"
echo "      __  __ _____ _____  _    ____  ____  _     ___ ___ _____"
echo "     |  \/  | ____|_   _|/ \  / ___||  _ \| |   / _ \_ _|_   _|"
echo "     | |\/| |  _|   | | / _ \ \___ \| |_) | |  | | | | |  | |"
echo "     | |  | | |___  | |/ ___ \ ___) |  __/| |__| |_| | |  | |"
echo "     |_|  |_|_____| |_/_/   \_\____/|_|   |_____\___/___| |_|"
sleep 0.2
echo -e "$G                   Cesar Hacker The Gray"
echo
sleep 0.3
printf "\n$G ::::::::::::::: Cargandoooo Metasploit :::::::::::::::$W"

	if [ -e $PREFIX/bin/msfconsole ] && [ -e $PREFIX/bin/msfvenom ]; then
		echo
		cd $HOME/metasploit-framework
		printf "$Y Intentamos correr msfconsole$W"
		msfconsole
	else
		echo
		cd $HOME/metasploit-framework
		printf "$Y Intentamos correr msfconsole$W"
                ruby msfconsole
	fi
echo "
"
if [ -e ~/version ]; then
	rm ~/version
fi
echo
rm -rf $HOME/version
echo
echo -e "$R Error"
sleep 0.5
echo -e "$R Metasploit no se instalo"
sleep 0.5
echo -e "$R Revisa si la version $version si existe"
sleep 0.5
echo -e "$R contactame https://t.me/CesarGray"
sleep 0.4
echo -e "$C Apodado como"
sleep 0.5
echo -e "$Y Cesar Hacker The Gray"
sleep 0.5
echo -e "$C Channel $R https://www.youtube.com/channel/UCjs0N8PbEo-se0r_4O_svNQ"
echo
echo
echo -e "$R Arracanda nuevamente $G msf"
echo
echo
sleep 4

