#! /data/data/com.termux/files/usr/bin/bash
	R='\033[1;31m'                                                          G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'






























echo
echo $(clear)
echo
echo -e "$R"
echo
echo "            " ____
echo "             / ___| _ __   __ _ _   _  ___ _ __"
echo "             \___ \|  _ \ / _  | | | |/ _ \  __|"
echo "              ___) | |_) | (_| | |_| |  __/ |"
echo "             |____/| .__/ \__,_|\__, |\___|_|"
echo "                   |_|          |___/"
echo -e "$Y           Cesar Hacker The Gray && Mickey"
echo
echo
sleep 3
echo -e "$C Multi"
sleep 2
echo -e "$C Payloads"
echo
sleep 4
echo $(clear)
echo
echo
echo
echo -e "$G Echo para accesos remotes"
echo
sleep 3
echo
echo
echo $(clear)
echo
echo
echo
echo -e "$C Checando Metasploit en HOME"
echo
sleep 5
cd $HOME/metasploit-framework
cd $HOME/
echo
echo $(clear)
echo
echo
echo
echo -e "$C Descargando requisitos"
echo
sleep 3
pkg update && pkg upgrade -y
pkg install python2 -y
pkg install git -y
pkg install wget php curl vim -y
echo
echo $(clear)
echo
echo
echo
echo -e "$C cLonando el repositorio backdoor"
echo
echo -e "$W Clonig.."
echo
echo
echo
echo
sleep 3
rm -rf $HOME/Spayer
git clone https://github.com/Cesar-Hack-Gray/Spayer
echo $(clear)
echo
echo
sleep 2
echo -e "$R Cesar Hacker The Gray"
echo
sleep 4
echo -e "$C Mickey"
echo
sleep 4
cd $HOME
echo
	echo $(wget https://raw.githubusercontent.com/Cesar-Hack-Gray/release-download/master/Spayer_install)

echo $(clear)

chmod 777 Spayer_install
bash Spayer_install
echo

