#! /data/data/com.termux/files/usr/bin/bash
	
	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'
	echo $(clear)
echo
echo
echo
printf "$G"
echo "      ___ _   _     _ _____ ____ _____ ___ _   _  ____"
echo "     |_ _| \ | |   | | ____/ ___|_   _|_ _| \ | |/ ___|"
echo "      | ||  \| |_  | |  _|| |     | |  | ||  \| | |  _"
echo "      | || |\  | |_| | |__| |___  | |  | || |\  | |_| |"
echo "     |___|_| \_|\___/|_____\____| |_| |___|_| \_|\____|"
echo -e "$R               CESAR HACKER THE GRAY"
echo
echo
sleep 7
echo
echo
echo
echo -e "$G SSSSSSSSSSSSSSSSSSSSSSSSSSS"
echo -e "$C [Gray] Checando Metasploit"
echo -e "$G SSSSSSSSSSSSSSSSSSSSSSSSSS"
echo
sleep 6
cd $HOME/metasploit-framework
cd $HOME
echo
echo
echo $(clear)
echo
echo
echo -e "$Y @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo -e "$C [Gray] $R Checando los repositorios existentes"
echo -e "$Y @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo
sleep 5
rm -rf $HOME/Injector
rm -rf $HOME/apktool
echo
echo
echo
echo
echo $(clear)
echo
echo
echo
echo -e "$G **************************"
echo -e "$C [Gray] $R Instalando datos"
echo -e "$G **************************"
echo
echo $(clear)
echo
echo
pkg update && pkg upgrade
pkg install git python2 php curl apksigner unzip wget -y
echo
echo
echo
echo
echo $(clear)
echo
echo
echo -e "$G ============================"
echo -e "$C [Gray] $R Instalando sistema"
echo -e "$G ============================$G"
echo
echo
git clone https://github.com/hax4us/apktool
echo
echo $(clear)
echo
echo -e "$G *****************************"
echo -e "$C [Gray] $R Instalando Injector"
echo -e "$G *****************************$G"
echo
echo
git clone https://github.com/Cesar-Hacker/Injector
echo
echo $(clear)
echo
echo
echo -e "$G MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo -e "$C [Gray] $R Instalando repositorios"
echo -e "$G MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo
echo
mkdir -p $HOME/Injector/Gray
mkdir -p $HOME/Injector/Cesar
mkdir -p $HOME/Injector/apk
echo
echo
echo $(clear)
echo
echo
echo
echo -e "$G ################################"
echo -e "$C [Gray] $R Ejecutandooo espera"
echo -e "$G ################################"
echo
sleep 8
rm -rf $HOME/Injector/CesarGray
cd $HOME/Injector
	echo $(wget https://raw.githubusercontent.com/Cesar-Hack-Gray/release-download/master/CesarGray)
	echo $(clear)
chmod 777 $HOME/Injector/CesarGray
bash $HOME/Injector/CesarGray


